### ISSUE TITLE
Xlsx files are automatically downloaded when page opens

### ISSUE THREAD

**Issue by Criccle** [mendix/FileDocumentViewer#14]
When a user uploads an xlsx file and I want to use this document viewer to show all attached filedocuments (since they might also be jpg, pdf, png, whatever) it automatically starts to download the xlsx. This is not expected behavior and would be great if fixed!

**Comment by rockinator** [comment]
We have a similar issue with files being downlaoded if the document viewer cannot show them. This is, for our use case, not desired behaviour and frankly quite annoying. Would be great if we could have an option that makes the File Document Viewer simply ignore files that are not viewable, instead of downloading them all the time.

**Comment by JelteMX** [comment]
This is literally in the documentation:

> Please take note that this will only work for Documents that can normally be viewed in the browser. We support viewing PDF either natively (Chrome, Firefox) or through PDF.js. Files like Word or Excel are usually not viewable in the browser. If you try this with the FileDocumentViewer, the browser will not view the document, but download it.

This is mostly used for PDFs. I am closing this issue
