### ISSUE TITLE
DocViewer within listening data view.

### ISSUE THREAD

**Issue by rickyv3** [mendix/FileDocumentViewer#7]
Hello,

We are attempting to utilize the DocViewer widget within a listening data view (Mx version 5.21.1) to enable our users to view the document(s) they have already uploaded without having to pop-up / download the document. 
![docviewergithub](https://cloud.githubusercontent.com/assets/13573078/13577732/a1a8ad1a-e459-11e5-891d-e8fd641e6141.jpg)

However, we have been unable to get the document to show up within the widget in the form. Note that when we pop-out the document using the widget the appropriate document is generated and downloaded.

We also upload documents to AWS, thus we have an entity titled AWSFileDocument that inherits from System.FileDocument.

Thank you for the help,
Ricky

**Comment by JelteMX** [comment]
Can you confirm that you are using the latest version of this widget, [v2.1.1](https://github.com/mendix/FileDocumentViewer/releases/tag/v2.1.1)? If this is the case, you might want to send a test-project to community [at] mendix.com and I will have a look at it. In our test-project everything is working fine. Also, which browser are you using?

**Comment by rickyv3** [comment]
Google Chrome: Version 48.0.2564.116 m

Yes, I have imported v2.1.1. I will try to put together a test project and release it soon. 

Thank you,
Ricky

**Comment by JelteMX** [comment]
@rickyv3 Can you check if this issue is fixed using [version 2.1.1](https://github.com/mendix/FileDocumentViewer/releases/tag/v2.2.1)? We have seen some issues with the Document Viewer and have fixed some, I don't know if this relates to your problem as well.

Also, is this problem on your desktop or on a mobile device? If it is the latter, you might want to check the '**Use PDF js**' option (in the case your documents are PDF files). See [documentation](https://github.com/mendix/FileDocumentViewer#pdfjs-support)
